config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"
  get 'noticias' => 'home#new', as: :new_post
  post 'noticias' => 'home#create'
  get 'noticias/:id' => 'home#edit', as: :edit_post
  post 'noticias/:id' => 'home#update'
  delete 'noticias/:id' => 'home#destroy', as: :destroy_post
  get 'horarios' => 'home#horarios', as: :horarios
  get 'horarios/:id' => 'home#edit_hora', as: :edit_hora
  post 'horarios/:id' => 'home#update_hora'
  
  #rutas de asignaturas
  get 'asignaturas' => 'asignaturas#new', as: :asignatura
  post 'asignaturas' => 'asignaturas#create'
  get 'asignaturas/:id' => 'asignaturas#edit', as: :edit_asignatura
  post 'asignaturas/:id' => 'asignaturas#update'
  delete 'asignaturas/:id' => 'asignaturas#destroy', as: :destroy_asignatura
  
  #rutas usuario
  get 'AceptarUsuarios' => 'users#show', as: :aceptar_usuarios
  delete 'user/:id' => 'users#destroy', as: :destroy_user
  get 'ModificarUsuarios' => 'users#edit', as: :edit_multiple_users
  put 'ModificarUsuarios' => 'users#update', as: :update_multiple_users
  
  #rutas alumno
  get 'alumnos' => 'alumnos#show', as: :alumno
  get 'alumnos/:id' => 'alumnos#edit', as: :edit_alumno
  get 'mi_info' => 'alumnos#show_grades', as: :show_grades_alumnos
  post 'alumnos/:id' => 'alumnos#update'
  get 'alumnos/editar' => 'alumnos#edit', as: :edit_multiple_alumnos
  put 'alumnos/editar' => 'alumnos#update', as: :update_multiple_alumnos
  
  #rutas profesor
  get 'profesores' => 'profesores#show', as: :profesor
  get 'profesores/:id' => 'profesores#edit', as: :edit_profesor
  post 'profesores/:id' => 'profesores#update'
  get 'subir_notas' => 'profesores#update_grades', as: :update_grades
  get 'subir_notas/:id/:periodo' => 'profesores#update_selected_grade', as: :update_selected_grade
  get 'mostrar_notas/:id' => 'profesores#update_selected_grade_notas', as: :update_selected_grade_notas
  put 'subir_notas/:id/:periodo' => 'profesores#update', as: :update_selected_grade_method
  get 'mis_alumnos' => 'profesores#alumnos', as: :mis_alumnos
  get 'mis_alumnos/:id' => 'profesores#info_alumno', as: :info_alumno
  
  #rutas administrador
  get 'configuracion' => 'users#configuracion', as: :configuracion
  post 'inscripcion/periodo_recuperacion'
  post 'inscripcion/cerrar_anio'
  post 'inscripcion/promover_alumnos'
  #rutas aula
  get 'aulas/crear' => 'aulas#new', as: :create_aula
  post 'aulas/crear' => 'aulas#create'
  get 'aulas' => 'aulas#show', as: :aulas
  delete 'aulas/:id' => 'aulas#destroy', as: :destroy_aula
  get 'aulas/:id' => 'aulas#edit', as: :edit_aula
  post 'aulas/:id' => 'aulas#update'
  
  #rutas curso
  get 'cursos' => 'cursos#show', as: :cursos
  get 'cursos/crear' => 'cursos#new', as: :create_curso
  post 'cursos/crear' => 'cursos#create'
  get 'cursos/:id' => 'cursos#edit', as: :edit_curso
  post 'cursos/:id' => 'cursos#update'
  get 'inscripcion/:id' => 'cursos#new_inscripcion', as: :inscripcion_new
  get 'inscripcion/:id/crear' => 'cursos#crear_inscripcion', as: :new_multiple_inscripcion
  get 'cursos/notas/:id' => 'cursos#update_curso_notas', as: :update_curso_notas
  
  #rutas inscripcion
  get 'inscripciones' => 'inscripcion#show', as: :inscripcion
  put 'subir_notas' => 'inscripcion#update', as: :update_multiple_notas
  
  
end

app/controllers/profesores_controller.rb
class ProfesoresController < ApplicationController
    def show
        @users = User.where(rol: 'Profesor')
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @users = User.find(params[:id])
        if @users.update(profesor_params)
            flash[:success] = "Profesor editado exitosamente!"
            redirect_to '/profesores'
        else
            flash[:error] = "Hubo un error al editar el Profesor."
            redirect_to '/profesores'
        end
    end
    def update_grades
        @notas = Curso.where("profesorID = ? and activo = true", session[:user_id])
    end
    def update_selected_grade
        @notas = Inscripcion.where("cursoID = ? AND periodo = ?", params[:id], params[:periodo])
        respond_to do |format|
            format.html
            format.json
            format.pdf {
                render template: 'profesores/listado_alumnos', 
                pdf: "Listado_alumnos", 
                orientation: 'Landscape',
                page_size: 'Letter'
            }
        end
    end
    def update_selected_grade_notas
        @notas = Inscripcion.where("cursoID = ?", params[:id]).order(:alumnoID)
        respond_to do |format|
            format.html
            format.json
            format.pdf {
                render template: 'profesores/notas_alumnos', 
                pdf: "Listado_alumnos", 
                orientation: 'Landscape',
                page_size: 'Letter'
            }
        end
    end
    def alumnos
        @mis_alumnos = User.where(profesorID: session[:user_id])
    end
    def info_alumno
        @alumno = User.find(params[:id])
        respond_to do |format|
            format.html
            format.json
            format.pdf {
                render template: 'profesores/info_alumno', 
                pdf: @alumno.name, 
                #orientation: 'Landscape',
                page_size: 'Letter'
            }
        end
    end
    private
        def profesor_params
            params.require(:user).permit(:name, :email, :carnet, :activo)
        end
end

app/helpers/profesores_helper.rb
module ProfesoresHelper
end

app/views/profesores/alumnos.html.erb
<h1>Listado de mis alumnos</h1>
<table id="example" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Grado</th>
        <th>Activo</th>
        <th>Información</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Grado</th>
        <th>Activo</th>
        <th>Información</th>
    </tr>
  </tfoot>
  <tbody>
    <% @mis_alumnos.each do |user| %> 
        <tr>
            <th><%= user.name %></th>
            <th><%= user.email %></th>
            <th><%= user.grado %></th>
            <th>
            <% if user.activo === "1" %>
                <%= image_tag("checkmark.png", {border: 0, width: 25, height: 25}) %>
            <% else %>
                <%= image_tag("cancel.png", {border: 0, width: 25, height: 25}) %>
            <% end %>
            </th>
            <th><%= link_to "Información", info_alumno_path(user), class: "btn btn-info" %></th>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/profesores/edit.html.erb
<h1>Editar Profesor</h1>
</br>
<div class="well">   
  <%= form_for :user do |f| %>
  <div class="row">
    <p class="col-md-4">
      <%= f.label :name, 'Nombre completo'  %><br>
      <%= f.text_field :name, :class => 'form-control' %>
    </p>
  </div>
  <div class="row">
    <p class="col-md-4">
      <%= f.label :email, 'Correo electronico' %><br>
      <%= f.text_field :email, :class => 'form-control' %>
    </p>
  </div>
  <div class="row">
    <p class="col-md-4">
      <%= f.label :carnet, 'Carnet' %><br>
      <%= f.text_field :carnet, :class => 'form-control' %>
    </p>
  </div>
  <div class="row">
    <p class="col-md-4">
      <%= f.label :activo, 'Activo' %><br>
      <%= f.check_box :activo, :class => 'form-control' %>
    </p>
  </div>
    
</div>
<p>
  <%= f.submit 'Editar', :class => 'btn btn-primary' %>
</p>
<% end %>
</br></br></br>

app/views/profesores/info_alumno.html.erb
<h1>Información de Alumno</h1>
    </br>
    <div><%= link_to "Descargar", info_alumno_path(@alumno.id, format: :pdf), class: "btn btn-info" %></div>
    </br>
    
    <div class="well">
          <div class="row">
            <div class="col-md-5"> <h4>Nombre completo: <%= @alumno.name %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"> <h4>Correo Electronico: <%= @alumno.email %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Carnet: <%= @alumno.carnet %></h4> </div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Profesor Encargado: <%= User.find(@alumno.profesorID).name %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"> <h4>Estudiante activo: <%= @alumno.activo %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4> Grado: <%= @alumno.grado %>°</h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4> Fecha de nacimiento: <%= @alumno.fecha_nac %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"> <h4> Centro Escolar Anterior: <%= @alumno.Centro_esc_ant %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4> Religion: <%= @alumno.religion %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Telefono de casa: <%= @alumno.tel_casa %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"> <h4>Enfermedades que padece: <%= @alumno.enfermedades %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"> <h4>Departamento: <%= @alumno.departamento %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"> <h4>Municipio: <%= @alumno.municipio %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Barrio: <%= @alumno.barrio %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Colonia: <%= @alumno.colonia %></h4></div>
          </div>
          </br></br>
          <div class="row">
            <div class="col-md-5"> <h4>Nombre del padre: <%= @alumno.nombre_padre %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Telefono padre: <%= @alumno.tel_padre %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Correo padre: <%= @alumno.correo_padre %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Ocupacion padre: <%= @alumno.ocupacion_padre %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Lugar de trabajo padre: <%= @alumno.lugar_trabajo_padre %></h4></div>
          </div>
          </br></br>
          <div class="row">
            <div class="col-md-5"><h4>Nombre madre: <%= @alumno.nombre_madre %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Telefono madre: <%= @alumno.tel_madre %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Correo madre: <%= @alumno.correo_madre %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Ocupacion madre: <%= @alumno.ocupacion_madre %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Lugar de trabajo madre: <%= @alumno.lugar_trabajo_madre %></h4></div>
            <div class="col-md-1"></div>
          </div>
          </br></br>
          <div class="row">
            <div class="col-md-5"><h4>Nombre encargado: <%= @alumno.nombre_enc %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Correo encargado: <%= @alumno.correo_enc %></h4></div>
          </div>
          </br>
          <div class="row">
            <div class="col-md-5"><h4>Telefono encargado: <%= @alumno.tel_enc %></h4></div>
            <div class="col-md-1"></div>
          </div>
          </br></br>
          <div class="row">
            <div class="col-md-5"><h4>En caso de emergencia: <%= @alumno.en_caso_emergencia %></h4></div>
            <div class="col-md-1"></div>
            <div class="col-md-5"><h4>Telefono de emergencia: <%= @alumno.tel_emergencia %></h4></div>
          </div>
          </br>
        </div>
</div>

app/views/profesores/info_alumno.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <style>  
  *{
    text-align: left;
  }
  table {
    border: 1px solid black;
  }
  
  h4 {
    font-size: 12px;
  }
  </style>
    <title> <%= @alumno.name %></title>
</head>
<h2>Informacion del alumno <br/> <%= @alumno.name %></h2>
<br/>
<h3>Informacion general</h3>
<table style="width:100%">
  <tr>
    <th style="width:50%"><h4>Nombre completo: <%= @alumno.name %></h4></th>
    <th style="width:50%"><h4>Correo Electronico: <%= @alumno.email %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Carnet: <%= @alumno.carnet %></h4></th>
    <th style="width:50%"><h4>Profesor Encargado: <%= User.find(@alumno.profesorID).name %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Estudiante activo: <%= @alumno.activo %></h4></th>
    <th style="width:50%"><h4> Grado: <%= @alumno.grado %> Grado</h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Fecha de nacimiento: <%= @alumno.fecha_nac %></h4></th>
    <th style="width:50%"><h4> Centro Escolar Anterior: <%= @alumno.Centro_esc_ant %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Religion: <%= @alumno.religion %></h4></th>
    <th style="width:50%"><h4>Telefono de casa: <%= @alumno.tel_casa %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Enfermedades que padece: <%= @alumno.enfermedades %></h4></th>
    <th style="width:50%"></th>
  </tr>
</table>
<br/>
<h3>Direccion</h3>
<table style="width:100%">
  <tr>
    <th style="width:50%"><h4>Departamento: <%= @alumno.departamento %></h4></th>
    <th style="width:50%"><h4>Municipio: <%= @alumno.municipio %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Barrio: <%= @alumno.barrio %></h4></th>
    <th style="width:50%"><h4>Colonia: <%= @alumno.colonia %></h4></th>
  </tr>
</table>
<br/>
<h3>Informacion del Padre</h3>
<table style="width:100%">
  <tr>
    <th style="width:50%"><h4>Nombre del padre: <%= @alumno.nombre_padre %></h4></th>
    <th style="width:50%"><h4>Telefono padre: <%= @alumno.tel_padre %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Correo padre: <%= @alumno.correo_padre %></h4></th>
    <th style="width:50%"><h4>Ocupacion padre: <%= @alumno.ocupacion_padre %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Lugar de trabajo padre: <%= @alumno.lugar_trabajo_padre %></h4></th>
    <th style="width:50%"></th>
  </tr>
</table>
<br/>
<h3>Informacion de la Madre</h3>
<table style="width:100%">
  <tr>
    <th style="width:50%"><h4>Nombre madre: <%= @alumno.nombre_madre %></h4></th>
    <th style="width:50%"><h4>Telefono madre: <%= @alumno.tel_madre %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Correo madre: <%= @alumno.correo_madre %></h4></th>
    <th style="width:50%"><h4>Ocupacion madre: <%= @alumno.ocupacion_madre %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Lugar de trabajo madre: <%= @alumno.lugar_trabajo_madre %></h4></th>
    <th style="width:50%"></th>
  </tr>
</table>
<br/>
<h3>Informacion del Encargado</h3>
<table style="width:100%">
  <tr>
    <th style="width:50%"><h4>Nombre encargado: <%= @alumno.nombre_enc %></h4></th>
    <th style="width:50%"><h4>Correo encargado: <%= @alumno.correo_enc %></h4></th>
  </tr>
  <tr>
    <th style="width:50%"><h4>Telefono encargado: <%= @alumno.tel_enc %></h4></th>
    <th style="width:50%"></th>
  </tr>
</table> 
  <br/>
<h3>En caso de emergencia</h3>
<table style="width:100%">
  <tr>
    <th style="width:50%"><h4>Persona responsable: <%= @alumno.en_caso_emergencia %></h4></th>
    <th style="width:50%"><h4>Telefono de emergencia: <%= @alumno.tel_emergencia %></h4></th>
  </tr>
</table>
</html>

app/views/profesores/listado_alumnos.pdf.erb
<!DOCTYPE html>
<html>
<head>
    <title>Listado de alumnos</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
    <body>
        <h2>Listado de alumnos</h2>
        <%= form_tag update_multiple_notas_path, method: :put do %>
  <table style="width:100%">
  	<tread>
	  <tr>
        <th>Alumno</th>
        <th style="color:white">_________________________________________________</th>
      </tr>
  	</tread>
    <tbody>
    	<% @notas.each do |nota| %>
        <%= fields_for "notas[]", nota do |f| %>
          <tr>
            <th><%= User.find(nota.alumnoID).name %></th>
            <th></th>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>
</br></br></br>
    </body>
</html>

app/views/profesores/notas_alumnos.pdf.erb
<!DOCTYPE html>
<html>
<head>
    <title>Notas de alumnos</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
    <body>
        <h2>Notas de alumnos del curso <%= Curso.find(params[:id]).cursoID %></h2>
        <%= form_tag update_multiple_notas_path, method: :put do %>
  <table style="width:100%">
  	<tread>
	  <tr>
        <th>Alumno</th>
        <th>Periodo</th>
        <th>Eval1</th>
        <th>Eval2</th>
        <th>Eval3</th>
        <th>Eval4</th>
        <th>Eval5</th>
        <th>Eval6</th>
        <th>Eval7</th>
        <th>Eval8</th>
        <th>Eval9</th>
      </tr>
  	</tread>
    <tbody>
    	<% @notas.each do |nota| %>
        <%= fields_for "notas[]", nota do |f| %>
          <tr>
            <th><%= User.find(nota.alumnoID).name %></th>
            <th><%= nota.periodo %></th>
            <th><%= nota.eval1 * 1.0 %></th>
            <th><%= nota.eval2 * 1.0 %></th>
            <th><%= nota.eval3 * 1.0 %></th>
            <th><%= nota.eval4 * 1.0 %></th>
            <th><%= nota.eval5 * 1.0 %></th>
            <th><%= nota.eval6 * 1.0 %></th>
            <th><%= nota.eval7 * 1.0 %></th>
            <th><%= nota.eval8 * 1.0 %></th>
            <th><%= nota.eval9 * 1.0 %></th>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>
</br></br></br>
    </body>
</html>

app/views/profesores/show.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>
<h1>Lista de Profesores</h1>
<table id="example" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Editar</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Editar</th>
    </tr>
  </tfoot>
  <tbody>
    <% @users.each do |user| %> 
        <tr>
            <th><%= user.name %></th>
            <th><%= user.email %></th>
            <th><%= link_to "Editar", edit_profesor_path(user), :class => 'btn btn-primary' %></th>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/profesores/update_grades.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>
<h1>Subir notas</h1>
</br>
<table id="example" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
        <th>Curso</th>
        <th>Asignatura</th>
        <th>Horario</th>
        <th>Periodo 1</th>
        <th>Periodo 2</th>
        <th>Periodo 3</th>
        <th>Periodo 4</th>
        <th>Periodo de Recuperacion</th>
        <th>Listado</th>
        <th>Notas</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
        <th>Curso</th>
        <th>Asignatura</th>
        <th>Horario</th>
        <th>Periodo 1</th>
        <th>Periodo 2</th>
        <th>Periodo 3</th>
        <th>Periodo 4</th>
        <th>Periodo de Recuperacion</th>
        <th>Listado</th>
        <th>Notas</th>
    </tr>
  </tfoot>
  <tbody>
    <% @notas.each do |notas| %> 
        <tr>
            <th><%= notas.cursoID %></th>
            <th><%= Asignatura.find(notas.asignaturaID).nombre %></th>
            <th><%= Curso.find(notas.profesorID).horario %></th>
            <th><%= link_to "Notas Periodo 1", update_selected_grade_path(notas,1) %></th>
            <th><%= link_to "Notas Periodo 2", update_selected_grade_path(notas,2) %></th>
            <th><%= link_to "Notas Periodo 3", update_selected_grade_path(notas,3) %></th>
            <th><%= link_to "Notas Periodo 4", update_selected_grade_path(notas,4) %></th>
            <th><%= link_to "Periodo de Recuperacion", update_selected_grade_path(notas,5) %></th>
            <th><%= link_to "Listado", update_selected_grade_path(notas,1, format: :pdf), class: "btn btn-info" %></th>
            <th><%= link_to "Notas", update_selected_grade_notas_path(notas, format: :pdf), class: "btn btn-info" %></th>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/profesores/update_selected_grade.html.erb
<h1>Subir Notas</h1>
</br>
<%= form_tag update_multiple_notas_path, method: :put do %>
  <table class="table">
    <tread>
      <th></th>
      <th>|</th>
      <th></th>
      <th>Actividades(35%)</th>
      <th></th>
      <th>|</th>
      <th></th>
      <th>Integracion(35%)</th>
      <th></th>
      <th>|Examen(30%)</th>
    </tread>
  	<tread>
	    <tr>
        <th>Alumno</th>
        <th>Actividad (5%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (5%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Examen (30%)</th>
      </tr>
  	</tread>
    <tbody>
    	<% @notas.each do |nota| %>
        <%= fields_for "notas[]", nota do |f| %>
          <tr>
            <th><%= User.find(nota.alumnoID).name %></th>
            <th><%= f.number_field :eval1, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval2, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval3, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval4, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval5, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval6, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval7, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval8, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval9, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
    <div class="actions">
        <%= submit_tag 'Subir notas', :class => 'btn btn-primary' %>
    </div>
    
<% end %>
</br></br></br>