config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"
  get 'noticias' => 'home#new', as: :new_post
  post 'noticias' => 'home#create'
  get 'noticias/:id' => 'home#edit', as: :edit_post
  post 'noticias/:id' => 'home#update'
  delete 'noticias/:id' => 'home#destroy', as: :destroy_post
  get 'horarios' => 'home#horarios', as: :horarios
  get 'horarios/:id' => 'home#edit_hora', as: :edit_hora
  post 'horarios/:id' => 'home#update_hora'
  
  #rutas de asignaturas
  get 'asignaturas' => 'asignaturas#new', as: :asignatura
  post 'asignaturas' => 'asignaturas#create'
  get 'asignaturas/:id' => 'asignaturas#edit', as: :edit_asignatura
  post 'asignaturas/:id' => 'asignaturas#update'
  delete 'asignaturas/:id' => 'asignaturas#destroy', as: :destroy_asignatura
  
  #rutas usuario
  get 'AceptarUsuarios' => 'users#show', as: :aceptar_usuarios
  delete 'user/:id' => 'users#destroy', as: :destroy_user
  get 'ModificarUsuarios' => 'users#edit', as: :edit_multiple_users
  put 'ModificarUsuarios' => 'users#update', as: :update_multiple_users
  
  #rutas alumno
  get 'alumnos' => 'alumnos#show', as: :alumno
  get 'alumnos/:id' => 'alumnos#edit', as: :edit_alumno
  get 'mi_info' => 'alumnos#show_grades', as: :show_grades_alumnos
  post 'alumnos/:id' => 'alumnos#update'
  get 'alumnos/editar' => 'alumnos#edit', as: :edit_multiple_alumnos
  put 'alumnos/editar' => 'alumnos#update', as: :update_multiple_alumnos
  
  #rutas profesor
  get 'profesores' => 'profesores#show', as: :profesor
  get 'profesores/:id' => 'profesores#edit', as: :edit_profesor
  post 'profesores/:id' => 'profesores#update'
  get 'subir_notas' => 'profesores#update_grades', as: :update_grades
  get 'subir_notas/:id/:periodo' => 'profesores#update_selected_grade', as: :update_selected_grade
  get 'mostrar_notas/:id' => 'profesores#update_selected_grade_notas', as: :update_selected_grade_notas
  put 'subir_notas/:id/:periodo' => 'profesores#update', as: :update_selected_grade_method
  get 'mis_alumnos' => 'profesores#alumnos', as: :mis_alumnos
  get 'mis_alumnos/:id' => 'profesores#info_alumno', as: :info_alumno
  
  #rutas administrador
  get 'configuracion' => 'users#configuracion', as: :configuracion
  post 'inscripcion/periodo_recuperacion'
  post 'inscripcion/cerrar_anio'
  post 'inscripcion/promover_alumnos'
  #rutas aula
  get 'aulas/crear' => 'aulas#new', as: :create_aula
  post 'aulas/crear' => 'aulas#create'
  get 'aulas' => 'aulas#show', as: :aulas
  delete 'aulas/:id' => 'aulas#destroy', as: :destroy_aula
  get 'aulas/:id' => 'aulas#edit', as: :edit_aula
  post 'aulas/:id' => 'aulas#update'
  
  #rutas curso
  get 'cursos' => 'cursos#show', as: :cursos
  get 'cursos/crear' => 'cursos#new', as: :create_curso
  post 'cursos/crear' => 'cursos#create'
  get 'cursos/:id' => 'cursos#edit', as: :edit_curso
  post 'cursos/:id' => 'cursos#update'
  get 'inscripcion/:id' => 'cursos#new_inscripcion', as: :inscripcion_new
  get 'inscripcion/:id/crear' => 'cursos#crear_inscripcion', as: :new_multiple_inscripcion
  get 'cursos/notas/:id' => 'cursos#update_curso_notas', as: :update_curso_notas
  
  #rutas inscripcion
  get 'inscripciones' => 'inscripcion#show', as: :inscripcion
  put 'subir_notas' => 'inscripcion#update', as: :update_multiple_notas
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :foto, FotoAlumnoUploader # Tells rails to use this uploader for this model.
    ROLES = ["Alumno", "Profesor", "Administrador"]
    validates :name, presence: true # Make sure the owner's name is present.
    
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
    
    def alumno?
        self.rol == 'Alumno'
    end
      
    def profesor?
        self.rol == 'Profesor'
    end
    
    def administrador?
        self.rol == 'Administrador'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @users = User.where(rol: nil)
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:success] = "Usuario eliminado exitosamente!"
        redirect_to '/AceptarUsuarios'
    end
    def edit
        begin
            @Users = User.where(rol: 'Profesor')
            @users = User.find(params[:users_ids])
        rescue
            flash[:error] = "Debe seleccionar al menos un alumno para editar!"
            redirect_to '/AceptarUsuarios'
        end
    end
    def update
        User.update(params[:users].keys, params[:users].values)
        flash[:success] = "Usuarios editados exitosamente!"
        redirect_to '/AceptarUsuarios'
    end
    
    def configuracion
        
    end
    
    private
    def user_params
        params.require(:user).permit(:name, :email, :rol, :carnet, :profesorID, :grado, :foto, :fecha_nac, :Centro_esc_ant, :religion, 
        :colonia, :departamento, :municipio, :barrio, :tel_casa, :enfermedades, :nombre_padre, :tel_padre, :correo_padre, :ocupacion_padre,
        :lugar_trabajo_padre, :nombre_madre, :tel_madre, :correo_madre, :ocupacion_madre, :lugar_trabajo_madre, :nombre_enc, :tel_enc, 
        :correo_enc, :en_caso_emergencia, :tel_emergencia, :activo) 
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/configuracion.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>
<h3>Configuracion</h3>
<h4>Configuracion de alumnos y cambio de grado</h4>
<div class="well">    
    <div class="row">
        <div class="col-md-4">
            <%= button_to 'Crear Periodo de Recuperacion', inscripcion_periodo_recuperacion_path, method: :post, :class => 'btn btn-danger' %>
        </div>
        <div class="col-md-8">
            <h4><strong>Se crearan todos los periodos de recuperacion, de manera que ahora todos los alumnos de tercer ciclo que no hayan logrando
            un 6 en la materia, se les creara un periodo de recuperacion a la materia que no aprobaron. </b> 
            Para los alumnos de bachilerato, la nota minima es 7, en caso no tengan 7 de nota en una materia en especifico se abre el 
            periodo de recuperacion en dicha materia. </b>Este proceso puede repetirse mas de una vez. </strong></h4>
        </div>
    </div>
</div>
</br>
<div class="well">    
    <div class="row">
         <div class="col-md-4">
                <%= button_to 'Promover Alumnos', inscripcion_promover_alumnos_path, method: :post, :class => 'btn btn-danger' %>
            </div>
            <div class="col-md-8">
                <h4><strong>Este boton ayuda a que todos los alumnos que hayan pasado todas sus materias (con 6 o mas para tercer ciclo y 
                7 para bachillerato), de manera automatica, el alumno pasara al siguiente grado. Para el caso de los alumnos que se graduan
                su estado pasa a ser desactivado, las notas del alumno graduado queda en el sistema. </br> 
                Esta funcion se debe correr una sola vez. Se hace la observacion que este proceso se debe correr justo antes de comenzar el 
                siguiente año escolar.</strong></h4>
            </div>
        </div>
    </div>
</div>
</br>
<div class="well">    
    <div class="row">
            <div class="col-md-4">
               <%= button_to 'Cerrar año escolar', inscripcion_cerrar_anio_path, method: :post, :class => 'btn btn-danger' %>
            </div>
            <div class="col-md-8">
                <h4><strong>ATENCION: El siguiente boton desactiva todas las funcionalidades del año actual, para poder limpiar y 
                comenzar de nuevo el siguiente año escolar. Se debe correr una sola vez justo antes de iniciar el siguiente año escolar.
                </strong></h4>
            </div>
        </div>
    </div>
</div>
</br></br></br></br>

app/views/users/edit.html.erb
<h1>Editar Usuarios</h1>
</br>
<%= form_tag update_multiple_users_path, method: :put do %>
    
        <table class="table">
          	<tread>
          	    <tr>
                    <th>Nombre</th>
                    <th>correo</th>
                    <th>Rol</th>
                    <th>Carnet</th>
                </tr>
          	</tread>
          	<tbody>
          	<% @users.each do |user| %>
          	    <%= fields_for "users[]", user do |f| %>
                <tr>
                    <th><%= f.text_field :name, :class => 'form-control' %></th>
                    <th><%= f.email_field :email, :class => 'form-control' %></th>
                    <th><%= f.select(:rol, User::ROLES) %></th>
                    <th><%= f.text_field :carnet, :class => 'form-control' %></th>
                </tr>
                <% end %>
            <% end %>
            </tbody>
        </table>
    <div class="actions">
        <%= submit_tag 'Editar Todos', :class => 'btn btn-primary' %>
    </div>
    
<% end %>
</br></br>

app/views/users/show.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>
<h1>Lista de usuarios</h1>
<h2>Proceso para aceptar usuarios al sistema </h2>
</br>
<%= form_tag edit_multiple_users_path, method: :get do %>
    <table id="example" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
      	    <th></th>
            <th>Nombre</th>
            <th>correo</th>
            <th>Rol</th>
            <th>Eliminar</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
      	    <th></th>
            <th>Nombre</th>
            <th>correo</th>
            <th>Rol</th>
            <th>Eliminar</th>
        </tr>
      </tfoot>
      <tbody>
        <% @users.each do |user| %> 
            <tr>
                <th><%= check_box_tag "users_ids[]", user.id  %></th>
                <th><%= user.name %></th>
                <th><%= user.email %></th>
                <th><%= user.rol %></th>
                <th><%= link_to "Eliminar", destroy_user_path(user), method: :delete, class: "btn btn-danger"  %></th>
            </tr>
        <% end %>
      </tbody>
    </table>
    <%= submit_tag "Editar", class: "btn btn-primary" %>
<% end %>
</br></br>