config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"
  get 'noticias' => 'home#new', as: :new_post
  post 'noticias' => 'home#create'
  get 'noticias/:id' => 'home#edit', as: :edit_post
  post 'noticias/:id' => 'home#update'
  delete 'noticias/:id' => 'home#destroy', as: :destroy_post
  get 'horarios' => 'home#horarios', as: :horarios
  get 'horarios/:id' => 'home#edit_hora', as: :edit_hora
  post 'horarios/:id' => 'home#update_hora'
  
  #rutas de asignaturas
  get 'asignaturas' => 'asignaturas#new', as: :asignatura
  post 'asignaturas' => 'asignaturas#create'
  get 'asignaturas/:id' => 'asignaturas#edit', as: :edit_asignatura
  post 'asignaturas/:id' => 'asignaturas#update'
  delete 'asignaturas/:id' => 'asignaturas#destroy', as: :destroy_asignatura
  
  #rutas usuario
  get 'AceptarUsuarios' => 'users#show', as: :aceptar_usuarios
  delete 'user/:id' => 'users#destroy', as: :destroy_user
  get 'ModificarUsuarios' => 'users#edit', as: :edit_multiple_users
  put 'ModificarUsuarios' => 'users#update', as: :update_multiple_users
  
  #rutas alumno
  get 'alumnos' => 'alumnos#show', as: :alumno
  get 'alumnos/:id' => 'alumnos#edit', as: :edit_alumno
  get 'mi_info' => 'alumnos#show_grades', as: :show_grades_alumnos
  post 'alumnos/:id' => 'alumnos#update'
  get 'alumnos/editar' => 'alumnos#edit', as: :edit_multiple_alumnos
  put 'alumnos/editar' => 'alumnos#update', as: :update_multiple_alumnos
  
  #rutas profesor
  get 'profesores' => 'profesores#show', as: :profesor
  get 'profesores/:id' => 'profesores#edit', as: :edit_profesor
  post 'profesores/:id' => 'profesores#update'
  get 'subir_notas' => 'profesores#update_grades', as: :update_grades
  get 'subir_notas/:id/:periodo' => 'profesores#update_selected_grade', as: :update_selected_grade
  get 'mostrar_notas/:id' => 'profesores#update_selected_grade_notas', as: :update_selected_grade_notas
  put 'subir_notas/:id/:periodo' => 'profesores#update', as: :update_selected_grade_method
  get 'mis_alumnos' => 'profesores#alumnos', as: :mis_alumnos
  get 'mis_alumnos/:id' => 'profesores#info_alumno', as: :info_alumno
  
  #rutas administrador
  get 'configuracion' => 'users#configuracion', as: :configuracion
  post 'inscripcion/periodo_recuperacion'
  post 'inscripcion/cerrar_anio'
  post 'inscripcion/promover_alumnos'
  #rutas aula
  get 'aulas/crear' => 'aulas#new', as: :create_aula
  post 'aulas/crear' => 'aulas#create'
  get 'aulas' => 'aulas#show', as: :aulas
  delete 'aulas/:id' => 'aulas#destroy', as: :destroy_aula
  get 'aulas/:id' => 'aulas#edit', as: :edit_aula
  post 'aulas/:id' => 'aulas#update'
  
  #rutas curso
  get 'cursos' => 'cursos#show', as: :cursos
  get 'cursos/crear' => 'cursos#new', as: :create_curso
  post 'cursos/crear' => 'cursos#create'
  get 'cursos/:id' => 'cursos#edit', as: :edit_curso
  post 'cursos/:id' => 'cursos#update'
  get 'inscripcion/:id' => 'cursos#new_inscripcion', as: :inscripcion_new
  get 'inscripcion/:id/crear' => 'cursos#crear_inscripcion', as: :new_multiple_inscripcion
  get 'cursos/notas/:id' => 'cursos#update_curso_notas', as: :update_curso_notas
  
  #rutas inscripcion
  get 'inscripciones' => 'inscripcion#show', as: :inscripcion
  put 'subir_notas' => 'inscripcion#update', as: :update_multiple_notas
  
  
end

app/models/curso.rb
class Curso < ActiveRecord::Base
    PERIODOS = ["1", "2", "3", "4"]
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
    def new
        @curso = Curso.new
        @Users = User.where(rol: 'Profesor')
        @Asignaturas = Asignatura.all
        @Aulas = Aula.all
    end
    def show
        @cursos = Curso.all
        @Users = User.where(rol: 'Profesor')
    end
    def create
        @curso = Curso.new(curso_params)
        if @curso.save
            flash[:success] = "Curso guardado exitosamente!"
            redirect_to '/cursos'
        else
            flash[:error] = "Hubo un error al almacenar el curso."
            redirect_to '/cursos'
        end
    end
    def edit
        @curso = Curso.find(params[:id])
        @Users = User.where(rol: 'Profesor')
        @Asignaturas = Asignatura.all
        @Aulas = Aula.all
    end
    def update
        @curso = Curso.find(params[:id])
        if @curso.update(curso_params)
            flash[:success] = "Curso editado exitosamente!"
            redirect_to '/cursos'
        else
            flash[:error] = "Hubo un error al editar el curso."
            redirect_to '/cursos'
        end
    end
    
    def update_curso_notas
        @notas = Inscripcion.where("cursoID = ?", params[:id])
    end
    def new_inscripcion
       @alumnos = User.where('rol = "Alumno" and activo = true and grado = "' + Aula.find(Curso.find(params[:id]).aulaID).grado + '"')
    end
    
    def crear_inscripcion
        @users = User.find(params[:users_ids])
        @users.each do |p|
            @aux = Inscripcion.where('activo = true and alumnoID = "' + p.id.to_s + '" and cursoID = "' + params[:id] + '"').first
            if @aux == nil 
                @inscripcion = Inscripcion.new
                @inscripcion.cursoID = params[:id]
                @inscripcion.alumnoID = p.id
                @inscripcion.periodo = 1
                @inscripcion.activo = true
                @inscripcion.save
                @inscripcion = Inscripcion.new
                @inscripcion.cursoID = params[:id]
                @inscripcion.alumnoID = p.id
                @inscripcion.periodo = 2
                @inscripcion.activo = true
                @inscripcion.save
                @inscripcion = Inscripcion.new
                @inscripcion.cursoID = params[:id]
                @inscripcion.alumnoID = p.id
                @inscripcion.periodo = 3
                @inscripcion.activo = true
                @inscripcion.save
                @inscripcion = Inscripcion.new
                @inscripcion.cursoID = params[:id]
                @inscripcion.alumnoID = p.id
                @inscripcion.periodo = 4
                @inscripcion.activo = true
                @inscripcion.save
            end
            flash[:success] = "Alumnos inscritos guardado exitosamente!"
        end
        
            redirect_to '/cursos'
    end
    private
        def curso_params
             params.require(:curso).permit(:cursoID, :asignaturaID, :profesorID, :aulaID, :horario, :activo)
        end
    
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/edit.html.erb
<h1>Editar Curso</h1>
</br>
<div class="well">
<%= form_for :curso do |f| %>
<div class="row">
  <p class="col-md-4">
    <%= f.label :cursoID, 'Curso ID'  %><br>
    <%= f.text_field :cursoID, :class => 'form-control' %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :aulaID, 'Aula' %><br>
    <% optAula = options_from_collection_for_select(@Aulas, 'id', 'aulaID') %>
    <%= f.select :aulaID,  optAula %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :asignaturaID, 'Asignatura' %><br>
    <% optAsignatura = options_from_collection_for_select(@Asignaturas, 'id', 'nombre') %>
    <%= f.select :asignaturaID,  optAsignatura %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :profesorID, 'Profesor asignado' %><br>
    <% optUser = options_from_collection_for_select(@Users, 'id', 'name') %>
    <%= f.select :profesorID,  optUser %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :activo, 'Aula activa' %><br>
    <%= f.check_box :activo, :class => 'form-control' %>
  </p>
</div>

  <p>
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </p>
<% end %>
</div>
</br></br>

app/views/cursos/edit_inscripcion.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>

<h1>Inscripción de alumnos</h1>

<h2>Para el curso <%= Curso.find(params[:id]).cursoID %></h2>
</br>
<%= form_tag new_multiple_inscripcion_path, method: :get do %>
    <table id="example" class="display" cellspacing="0" width="100%">
      <thead>
         <tr>
            <th></th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Grado</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
            <th></th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Grado</th>
        </tr>
      </tfoot>
      <tbody>
        <% @alumnos.each do |alumnos| %> 
            <tr>
                <th><%= check_box_tag "users_ids[]", alumnos.id  %></th>
                <th><%= alumnos.name %></th>
                <th><%= alumnos.email %></th>
                <th><%= alumnos.grado %> Grado</th>
            </tr>
        <% end %>
        </tbody>
    </table>
        <%= submit_tag "Guardar Selección" %>
<% end %>

app/views/cursos/new.html.erb
<h1>Nuevo Curso</h1>
</br>
<div class="well">
<%= form_for :curso do |f| %>
<div class="row">
  <p class="col-md-4">
    <%= f.label :cursoID, 'Curso ID'  %><br>
    <%= f.text_field :cursoID, :class => 'form-control' %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :aulaID, 'Aula' %><br>
    <% optAula = options_from_collection_for_select(@Aulas, 'id', 'aulaID') %>
    <%= f.select :aulaID,  optAula %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :asignaturaID, 'Asignatura' %><br>
    <% optAsignatura = options_from_collection_for_select(@Asignaturas, 'id', 'nombre') %>
    <%= f.select :asignaturaID,  optAsignatura %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :profesorID, 'Profesor asignado' %><br>
    <% optUser = options_from_collection_for_select(@Users, 'id', 'name') %>
    <%= f.select :profesorID,  optUser %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :horario, 'Horario'  %><br>
    <%= f.text_field :horario, :class => 'form-control' %>
  </p>
</div>
<div class="row">
  <p class="col-md-4">
    <%= f.label :activo, 'Curso activo' %><br>
    <%= f.check_box :activo, :class => 'form-control' %>
  </p>
</div>

  <p>
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </p>
<% end %>
</div>
</br></br>

app/views/cursos/new_inscripcion.html.erb
<% if flash[:success] %>
    <div class="alert alert-success">
        <%= flash[:success] %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>

<h1>Inscripción de alumnos</h1>

<h2>Para el curso <%= Curso.find(params[:id]).cursoID %></h2>
</br>
<%= form_tag new_multiple_inscripcion_path, method: :get do %>
    <table id="example" class="display" cellspacing="0" width="100%">
      <thead>
         <tr>
            <th></th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Grado</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
            <th></th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Grado</th>
        </tr>
      </tfoot>
      <tbody>
        <% @alumnos.each do |alumnos| %> 
            <tr>
                <th><%= check_box_tag "users_ids[]", alumnos.id  %></th>
                <th><%= alumnos.name %></th>
                <th><%= alumnos.email %></th>
                <th><%= alumnos.grado %> Grado</th>
            </tr>
        <% end %>
        </tbody>
    </table>
        <%= submit_tag "Guardar Selección", :class => 'btn btn-primary'  %>
        </br></br></br>
<% end %>

app/views/cursos/show.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>
<h1>Listado de Cursos</h1>

<%= link_to "Crear Curso", create_curso_path(), class: "btn btn-primary" %>
</br>
</br>
<table id="example" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
        <th>ID curso</th>
        <th>Aula</th>
        <th>Profesor</th>
        <th>Asignatura</th>
        <th>Horario</th>
        <th>Editar</th>
        <th>Definir Alumnos</th>
        <th>Notas</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
        <th>ID curso</th>
        <th>Aula</th>
        <th>Profesor</th>
        <th>Asignatura</th>
        <th>Horario</th>
        <th>Editar</th>
        <th>Definir Alumnos</th>
        <th>Notas</th>
    </tr>
  </tfoot>
  <tbody>
    <% @cursos.each do |curso| %> 
      <tr>
        <th><%= curso.cursoID %></th>
        <th><%= Aula.find(curso.aulaID).aulaID %></th>
        <th><%= User.find(curso.profesorID).name %></th>
        <th><%= Asignatura.find(curso.asignaturaID).nombre %></th>
        <th><%= Curso.find(curso.profesorID).horario %></th>
        <th><%= link_to "Editar", edit_curso_path(curso), class: "btn btn-success" %></th>
        <th><%= link_to "Inscribir", inscripcion_new_path(curso), class: "btn btn-warning" %></th>
        <th><%= link_to "Notas", update_curso_notas_path(curso.id), class: "btn btn-primary" %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cursos/update_curso_notas.html.erb
<h1>Subir Notas modo administrador</h1>
</br>
<%= form_tag update_multiple_notas_path, method: :put do %>
  <table class="table">
    <tread>
      <th></th>
      <th>|</th>
      <th></th>
      <th>Actividades(35%)</th>
      <th></th>
      <th>|</th>
      <th></th>
      <th>Integracion(35%)</th>
      <th></th>
      <th>|Examen(30%)</th>
    </tread>
  	<tread>
	    <tr>
        <th>Alumno</th>
        <th>Actividad (5%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (5%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Evaluacion (10%)</th>
        <th>Examen (30%)</th>
      </tr>
  	</tread>
    <tbody>
    	<% @notas.each do |nota| %>
        <%= fields_for "notas[]", nota do |f| %>
          <tr>
            <th><%= User.find(nota.alumnoID).name %></th>
            <th><%= f.number_field :eval1, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval2, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval3, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval4, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval5, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval6, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval7, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval8, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
            <th><%= f.number_field :eval9, :step => 0.01, :min => 0.00, :max => 10.0, :class => 'form-control' %></th>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
    <div class="actions">
        <%= submit_tag 'Subir notas', :class => 'btn btn-primary' %>
    </div>
    
<% end %>
</br></br></br>