config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  root to: "home#show"
  get 'noticias' => 'home#new', as: :new_post
  post 'noticias' => 'home#create'
  get 'noticias/:id' => 'home#edit', as: :edit_post
  post 'noticias/:id' => 'home#update'
  delete 'noticias/:id' => 'home#destroy', as: :destroy_post
  get 'horarios' => 'home#horarios', as: :horarios
  get 'horarios/:id' => 'home#edit_hora', as: :edit_hora
  post 'horarios/:id' => 'home#update_hora'
  
  #rutas de asignaturas
  get 'asignaturas' => 'asignaturas#new', as: :asignatura
  post 'asignaturas' => 'asignaturas#create'
  get 'asignaturas/:id' => 'asignaturas#edit', as: :edit_asignatura
  post 'asignaturas/:id' => 'asignaturas#update'
  delete 'asignaturas/:id' => 'asignaturas#destroy', as: :destroy_asignatura
  
  #rutas usuario
  get 'AceptarUsuarios' => 'users#show', as: :aceptar_usuarios
  delete 'user/:id' => 'users#destroy', as: :destroy_user
  get 'ModificarUsuarios' => 'users#edit', as: :edit_multiple_users
  put 'ModificarUsuarios' => 'users#update', as: :update_multiple_users
  
  #rutas alumno
  get 'alumnos' => 'alumnos#show', as: :alumno
  get 'alumnos/:id' => 'alumnos#edit', as: :edit_alumno
  get 'mi_info' => 'alumnos#show_grades', as: :show_grades_alumnos
  post 'alumnos/:id' => 'alumnos#update'
  get 'alumnos/editar' => 'alumnos#edit', as: :edit_multiple_alumnos
  put 'alumnos/editar' => 'alumnos#update', as: :update_multiple_alumnos
  
  #rutas profesor
  get 'profesores' => 'profesores#show', as: :profesor
  get 'profesores/:id' => 'profesores#edit', as: :edit_profesor
  post 'profesores/:id' => 'profesores#update'
  get 'subir_notas' => 'profesores#update_grades', as: :update_grades
  get 'subir_notas/:id/:periodo' => 'profesores#update_selected_grade', as: :update_selected_grade
  get 'mostrar_notas/:id' => 'profesores#update_selected_grade_notas', as: :update_selected_grade_notas
  put 'subir_notas/:id/:periodo' => 'profesores#update', as: :update_selected_grade_method
  get 'mis_alumnos' => 'profesores#alumnos', as: :mis_alumnos
  get 'mis_alumnos/:id' => 'profesores#info_alumno', as: :info_alumno
  
  #rutas administrador
  get 'configuracion' => 'users#configuracion', as: :configuracion
  post 'inscripcion/periodo_recuperacion'
  post 'inscripcion/cerrar_anio'
  post 'inscripcion/promover_alumnos'
  #rutas aula
  get 'aulas/crear' => 'aulas#new', as: :create_aula
  post 'aulas/crear' => 'aulas#create'
  get 'aulas' => 'aulas#show', as: :aulas
  delete 'aulas/:id' => 'aulas#destroy', as: :destroy_aula
  get 'aulas/:id' => 'aulas#edit', as: :edit_aula
  post 'aulas/:id' => 'aulas#update'
  
  #rutas curso
  get 'cursos' => 'cursos#show', as: :cursos
  get 'cursos/crear' => 'cursos#new', as: :create_curso
  post 'cursos/crear' => 'cursos#create'
  get 'cursos/:id' => 'cursos#edit', as: :edit_curso
  post 'cursos/:id' => 'cursos#update'
  get 'inscripcion/:id' => 'cursos#new_inscripcion', as: :inscripcion_new
  get 'inscripcion/:id/crear' => 'cursos#crear_inscripcion', as: :new_multiple_inscripcion
  get 'cursos/notas/:id' => 'cursos#update_curso_notas', as: :update_curso_notas
  
  #rutas inscripcion
  get 'inscripciones' => 'inscripcion#show', as: :inscripcion
  put 'subir_notas' => 'inscripcion#update', as: :update_multiple_notas
  
  
end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
    validates :asignaturaID, uniqueness: { case_sensitive: false, error_iguales: "No pueden haber materias repetidas" }
    validates :asignaturaID, :nombre, :presence => true
end

app/models/aula.rb
class Aula < ActiveRecord::Base
    GRADOS = ["7", "8", "9", "10", "11"]
    validates :aulaID, uniqueness: { case_sensitive: false, error_iguales: "No pueden haber aulas repetidas" }
end

app/models/curso.rb
class Curso < ActiveRecord::Base
    PERIODOS = ["1", "2", "3", "4"]
end

app/models/hora.rb
class Hora < ActiveRecord::Base
end

app/models/inscripcion.rb
class Inscripcion < ActiveRecord::Base
    
end

app/models/post.rb
class Post < ActiveRecord::Base
    mount_uploader :foto, FotoUploader # Tells rails to use this uploader for this model.
    validates :titulo, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :foto, FotoAlumnoUploader # Tells rails to use this uploader for this model.
    ROLES = ["Alumno", "Profesor", "Administrador"]
    validates :name, presence: true # Make sure the owner's name is present.
    
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
    
    def alumno?
        self.rol == 'Alumno'
    end
      
    def profesor?
        self.rol == 'Profesor'
    end
    
    def administrador?
        self.rol == 'Administrador'
    end
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
    def new
        @aula = Aula.new
        @Users = User.where(rol: 'Profesor')
    end
    def create
        @aula = Aula.new(aula_params)
        if @aula.save
            flash[:success] = "Aula guardada exitosamente!"
            redirect_to '/aulas'
        else
            flash[:error] = "Hubo un error al almacenar el Aula."
            redirect_to '/aulas'
        end
    end
    def show
        @aulas = Aula.all
    end
    def edit
        @aula = Aula.find(params[:id])
        @Users = User.where(rol: 'Profesor')
    end
    def update
        @aula = Aula.find(params[:id])
        if @aula.update(aula_params)
            flash[:success] = "Aula editada exitosamente!"
            redirect_to '/aulas'
        else
            flash[:error] = "Hubo un error al editar el aula."
            redirect_to '/aulas'
        end
    end
    def destroy
        @aula = Aula.find(params[:id])
        @aula.destroy
        flash[:success] = "Aula eliminada exitosamente!"
        redirect_to '/aulas'
    end 
    private
        def aula_params
            params.require(:aula).permit(:aulaID, :profesorID, :grado, :actual)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @posts = Post.limit(5).order('created_at DESC')
  end
  def new
    @post = Post.new
    @posts = Post.all
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Noticia publicada exitosamente!"
      redirect_to '/noticias'
    else
      render "new"
    end
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Noticia editada exitosamente!"
      redirect_to '/noticias'
    else
      flash[:error] = "Hubo un error al editar la noticia."
      redirect_to '/noticias'
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Noticia Eliminada exitosamente!"
    redirect_to '/noticias'
  end
  
  def horarios
    @horas = Hora.all
  end
  
  def edit_hora
    @hora = Hora.find(params[:id])
  end
  
  def update_hora
    @hora = Hora.find(params[:id])
    if @hora.update(params.require(:hora).permit(:titulo, :url))
      flash[:success] = "Horario editado exitosamente!"
      redirect_to '/horarios'
    else
      flash[:error] = "Hubo un error al editar el horario."
      redirect_to '/horarios'
    end
  end
  
  private 
    def post_params
      params.require(:post).permit(:titulo, :contenido, :foto)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inscripcion_helper.rb
module InscripcionHelper
end

app/helpers/profesores_helper.rb
module ProfesoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colegio Citalá</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <div id="page-wrap">
      <div class="container-fluid">
        <div class="navbar-form navbar-left">
          <%= link_to image_tag("boton_principal.png", border: 0), "/" %>
        </div>
        <div class="navbar-form navbar-right">
          <% if current_user %>
            <h4>Bienveido <strong><%= current_user.name %></strong>!</h4>
            <%= link_to "Desconectarse", signout_path, id: "sign_out" %>
          <% else %>
            <h4><%= link_to("Acceso Institucional", "https://citala-lievanov.c9users.io/auth/google_oauth2") %></h4>
          <% end %>
        </div>
      </div>
      </br>
      <ul class="nav nav-tabs nav-justified">
        
        <% if current_user && current_user.administrador? %> 
          <li><%= link_to "Asignaturas", asignatura_path() %></li>
          <li><%= link_to "Alumnos", alumno_path() %></li>
          <li><%= link_to "Profesores", profesor_path() %></li>
          <li><%= link_to "Usuarios", aceptar_usuarios_path() %></li>
          <li><%= link_to "Aulas", aulas_path() %></li>
          <li><%= link_to "Cursos", cursos_path() %></li>
          <li><%= link_to "Inscripciones", inscripcion_path() %></li>
          <li><%= link_to "Noticias", new_post_path() %></li>
          <li><%= link_to "Configuracion", configuracion_path() %></li>
        <% end %>
        
        <% if current_user && current_user.profesor? %> 
        <li><%= link_to "Mis Alumnos", mis_alumnos_path() %></li>
        <li><%= link_to "Subir Notas", update_grades_path() %></li>
        <% end %>
        
        <% if current_user && current_user.alumno? %> 
          <li><%= link_to "Mis Notas", show_grades_alumnos_path() %></li>
        <% end %>
        <li><%= link_to "Horarios", horarios_path() %></li>
      </ul>
      <div>
      </br>
      <%= yield %>
      </div>
    </div>
    <div style="background-color:#282828;color:#ADAFB2;">
        <center>
          <p>Colegio Citalá</p>
          <p>Colegio Lamatepec. A 600 metros sobre la calle que de la Carretera al Puerto de La Libertad conduce al Cantón Las Granadillas. </p>
          <p>Desvío hacia Comasagua. Santa Tecla. la Libertad. Tel. (503) 2534 8928</p>
          <p>www.citala.edu.sv</p>
          <p>informacion@citala.edu.sv</p>
        </center>
      </div>
  </div>
  
    
  </body>
</html>

app/views/layouts/bk_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colegio Citalá</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <div id="page-wrap">
      <div class="container-fluid">
        <div class="navbar-form navbar-left">
          <%= link_to image_tag("boton_principal.png", border: 0), "/" %>
        </div>
        <div class="navbar-form navbar-right">
          <% if current_user %>
            <h4>Bienvenido <strong><%= current_user.name %></strong>!</h4>
            <%= link_to "Desconectarse", signout_path, id: "sign_out" %>
          <% else %>
            <h4><%= link_to("Acceso Institucional", "https://citala-lievanov.c9users.io/auth/google_oauth2") %></h4>
          <% end %>
        </div>
      </div>
      </br>
      <ul class="nav nav-tabs nav-justified">
        
          <li><%= link_to "Asignaturas", asignatura_path() %></li>
          <li><%= link_to "Alumnos", alumno_path() %></li>
          <li><%= link_to "Profesores", profesor_path() %></li>
          <li><%= link_to "Usuarios", aceptar_usuarios_path() %></li>
          <li><%= link_to "Aulas", aulas_path() %></li>
          <li><%= link_to "Cursos", cursos_path() %></li>
          <li><%= link_to "Inscripciones", inscripcion_path() %></li>
          <li><%= link_to "Noticias", new_post_path() %></li>
          <li><%= link_to "Mis Alumnos", mis_alumnos_path() %></li>
          <li><%= link_to "Subir notas", update_grades_path() %></li>
          <li><%= link_to "Mis notas", show_grades_alumnos_path() %></li>
          <li><%= link_to "Configuracion", configuracion_path() %></li>
      </ul>
      <div>
      </br>
      <%= yield %>
      </div>
    </div>
    <div style="background-color:#282828;color:#ADAFB2;">
        <center>
          <p>Colegio Citalá</p>
          <p>Colegio Lamatepec. A 600 metros sobre la calle que de la Carretera al Puerto de La Libertad conduce al Cantón Las Granadillas. </p>
          <p>Desvío hacia Comasagua. Santa Tecla. la Libertad. Tel. (503) 2534 8928</p>
          <p>www.citala.edu.sv</p>
          <p>informacion@citala.edu.sv</p>
        </center>
      </div>
  </div>
  </body>
</html>

app/views/reports/info_alumno.pdf.erb
<%= wicked_pdf_stylesheet_link_tag 'pdf' %>
<h1>Lista de Alumnos</h1>
    </br>
    <%= form_tag edit_multiple_alumnos_path, method: :get do %>
        <table id="example" class="display" cellspacing="0" width="100%">
          <thead>
            <tr>
          	    <th></th>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Grado</th>
                <th>Activo</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
          	    <th></th>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Grado</th>
                <th>Activo</th>
            </tr>
          </tfoot>
          <tbody>
            <% @users.each do |user| %> 
                <tr>
                    <th><%= check_box_tag "users_ids[]", user.id  %></th>
                    <th><%= user.name %></th>
                    <th><%= user.email %></th>
                    <th><%= user.grado %></th>
                    <th>
                    <% if user.activo === "1" %>
                        <%= image_tag("checkmark.png", {border: 0, width: 25, height: 25}) %>
                    <% else %>
                        <%= image_tag("cancel.png", {border: 0, width: 25, height: 25}) %>
                    <% end %>
                    </th>
                </tr>
            <% end %>
          </tbody>
        </table>
        <%= submit_tag "Editar Selección" %>
    </br>
<% end %>

app/views/reports/mis_notas.pdf.erb
<h1>Mis notas</h1>
</br>
<table id="example" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
        <th>Materia</th>
        <th>Periodo</th>
        <th>Actividades(35%)</th>
        <th>Int(35%)</th>
        <th>Examen Periodo (30%)</th>
        <th>Nota Periodo</th>
        <th>Nota Acumulado</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
        <th>Materia</th>
        <th>Periodo</th>
        <th>Actividades(35%)</th>
        <th>Int(35%)</th>
        <th>Examen Periodo (30%)</th>
        <th>Nota Periodo</th>
        <th>Nota Acumulado</th>
    </tr>
  </tfoot>
  <tbody>
    <% @notas.each do |inscripcion| %> 
	    <tr>
            <% if inscripcion.periodo == 1 %>
              <th rowspan="4"> <%= Asignatura.find(Curso.find(inscripcion.cursoID).asignaturaID).nombre %> </th>
            <% end %>
            <th><%= inscripcion.periodo %></th>
            <th><%= ((inscripcion.eval1 * 0.1 ) + (inscripcion.eval2 * 0.30) + (inscripcion.eval3 * 0.30) + (inscripcion.eval4 * 0.30)).round(2) %></th>
            <th><%= ((inscripcion.eval5 * 0.1) + (inscripcion.eval6 * 0.30) + (inscripcion.eval7 * 0.30) + (inscripcion.eval8 * 0.30)).round(2) %></th>
            <th><%= inscripcion.eval9 %></th>
            <th><%= ((inscripcion.eval1 * 0.05) + (inscripcion.eval2 * 0.1) + (inscripcion.eval3 * 0.1) + (inscripcion.eval4 * 0.10) + (inscripcion.eval5 * 0.05) + (inscripcion.eval6 * 0.1) + (inscripcion.eval7 * 0.1) + (inscripcion.eval8 * 0.1) + (inscripcion.eval9 * 0.3)).round(2) %></th>
            <% if inscripcion.periodo == 1 %>
              <th rowspan="4"> <%= calcular_acumulado(inscripcion.alumnoID, inscripcion.cursoID).round(2) %> </th>
            <% end %>
        </tr>
    <% end %>
  </tbody>
</table>
</br></br></br>